# Generated by Django 5.1.1 on 2024-11-23 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_persona_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='persona',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Es staff'),
        ),
        migrations.AddField(
            model_name='persona',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Es superusuario'),
        ),
        migrations.AddField(
            model_name='persona',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='correo',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(max_length=250, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de usuario'),
        ),
    ]
