# Generated by Django 5.1.1 on 2024-12-09 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_puntuacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
